version: "3.9"

services:
  jupyterlab:
    image: jupyter/pgweb:test
    build:
      context: "."
      dockerfile: setup/Dockerfile
    container_name: pgweb-jupyterlab
    restart: always
    ports:
      - 8888:8888
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - "${PWD}:/home/jovyan/jupyter-pgweb-proxy"
  postgres:
    image: postgres:15.3-alpine
    hostname: postgres
    container_name: pgweb-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    name: db

